dbt_fundamentals_initiative:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres-database-dataroots.postgres.database.azure.com
      user: dataroots
      password: Postgres1
      port: 5432
      dbname: AdventureWorks
      schema: tom_vandorpe
      threads: 1
    