version: 2

sources:
  - name: AdventureWorks
    database: AdventureWorks 
    schema: hr_data  
    tables:
      - name: department
      - name: employee
      - name: employeedepartmenthistory
      - name: person
      


