
version: 2

models:
  - name: stg_department
    description: "department and Business Unit table"
    columns:
      - name: departmentid
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: department_name
        data_tests:
          - unique
          - not_null
      - name: business_unit
        data_tests:
          - not_null
      - name: modifieddate
        description: "Last date the entry is modified"
        data_tests:
          - not_null  
