version: 2

sources:
  - name: AdventureWorks
    database: AdventureWorks 
    schema: sales_data  
    tables:
      - name: customer
      - name: salesorderdetail
      - name: salesorderheader


